/**
 * Step 3: Budowa projektu Next.js
 * Generuje projekt Next.js przez AI i buduje go
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { mkdir, writeFile, copyFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { NextJSGenerator } from '../integrations/nextjs-generator.js';
import type { StepHandler, BuildContext, StepResult } from '../types/index.js';

const execAsync = promisify(exec);
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export class NextJSBuildStep implements StepHandler {
  name = '03-nextjs-build';
  description = 'Budowa projektu Next.js';

  async execute(context: BuildContext): Promise<StepResult> {
    const startTime = Date.now();

    try {
      const { config, analysis, strapiSchema, cursorPrompt } = context;

      if (!analysis || !cursorPrompt) {
        throw new Error('Brak analizy/prompta - uruchom najpierw krok analyze');
      }

      const workDir = config.workDir || process.cwd();
      const projectPath = join(workDir, 'build', config.projectName);

      if (config.verbose) {
        console.log(`[Next.js Build] Project path: ${projectPath}`);
      }

      // 1. Utwórz katalog projektu
      await mkdir(projectPath, { recursive: true });

      // 2. Generuj kod przez AI
      const generator = new NextJSGenerator(config.anthropic, config.verbose);
      
      const files = await generator.generateProject(
        analysis,
        cursorPrompt,
        strapiSchema,
        config.projectName
      );

      // 3. Zapisz wygenerowane pliki
      await generator.writeFiles(files, projectPath);

      // 4. Skopiuj template files
      await this.copyTemplateFiles(projectPath);

      // 5. Install dependencies
      if (config.verbose) {
        console.log('[Next.js Build] Installing dependencies...');
      }

      await execAsync('npm install', { cwd: projectPath });

      // 6. Build projekt
      if (config.verbose) {
        console.log('[Next.js Build] Building project...');
      }

      await execAsync('npm run build', { cwd: projectPath });

      context.nextjsPath = projectPath;
      context.buildPath = join(projectPath, 'out');

      return {
        step: this.name,
        status: 'completed',
        duration: Date.now() - startTime,
        message: `Projekt Next.js wygenerowany i zbudowany (${files.length} plików)`,
        data: {
          projectPath,
          buildPath: context.buildPath,
          filesGenerated: files.length,
        },
      };
    } catch (error) {
      return {
        step: this.name,
        status: 'failed',
        duration: Date.now() - startTime,
        message: `Błąd podczas budowy Next.js: ${(error as Error).message}`,
        error: error as Error,
      };
    }
  }

  /**
   * Kopiuje template files (globals.css, tsconfig.json, etc.)
   */
  private async copyTemplateFiles(projectPath: string): Promise<void> {
    const templatesDir = join(__dirname, '../templates');

    // Utwórz katalogi
    await mkdir(join(projectPath, 'src/app'), { recursive: true });

    // globals.css
    await copyFile(
      join(templatesDir, 'globals.css'),
      join(projectPath, 'src/app/globals.css')
    );

    // postcss.config.mjs
    await copyFile(
      join(templatesDir, 'postcss.config.mjs'),
      join(projectPath, 'postcss.config.mjs')
    );

    // tsconfig.json
    await copyFile(
      join(templatesDir, 'tsconfig.json'),
      join(projectPath, 'tsconfig.json')
    );

    // .gitignore
    const gitignore = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# misc
.DS_Store
*.pem

# debug
npm-debug.log*

# env files
.env*.local

# typescript
*.tsbuildinfo
next-env.d.ts
`;

    await writeFile(join(projectPath, '.gitignore'), gitignore);

    // README.md
    const readme = `# ${projectPath.split('/').pop()}

Generated by Site Builder.

## Development

\`\`\`bash
npm install
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`
`;

    await writeFile(join(projectPath, 'README.md'), readme);
  }

  canSkip(context: BuildContext): boolean {
    return false;
  }
}
